CREATE TABLE language (
  code char(3) NOT NULL, -- ISO 639-2
  iso_639_1 char(2),
  name VARCHAR(80) NOT NULL,
  french_name VARCHAR(80) NOT NULL,
  image varchar(256) default NULL,
  sort_order int default 999999,
  PRIMARY KEY (code)
);

INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('aar','aa','Afar','afar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('abk','ab','Abkhazian','abkhaze');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ace','','Achinese','aceh');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ach','','Acoli','acoli');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ada','','Adangme','adangme');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ady','','Adyghe; Adygei','adygh');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('afa','','Afro-Asiatic languages','afro-asiatiques, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('afh','','Afrihili','afrihili');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('afr','af','Afrikaans','afrikaans');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ain','','Ainu','anou');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('aka','ak','Akan','akan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('akk','','Akkadian','akkadien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('alb','sq','Albanian','albanais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ale','','Aleut','aloute');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('alg','','Algonquian languages','algonquines, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('alt','','Southern Altai','altai du Sud');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('amh','am','Amharic','amharique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ang','','English, Old (ca.450-1100)','anglo-saxon (ca.450-1100)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('anp','','Angika','angika');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('apa','','Apache languages','apaches, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ara','ar','Arabic','arabe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('arc','','Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)','aramen d''empire (700-300 BCE)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('arg','an','Aragonese','aragonais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('arm','hy','Armenian','armnien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('arn','','Mapudungun; Mapuche','mapudungun; mapuche; mapuce');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('arp','','Arapaho','arapaho');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('art','','Artificial languages','artificielles, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('arw','','Arawak','arawak');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('asm','as','Assamese','assamais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ast','','Asturian; Bable; Leonese; Asturleonese','asturien; bable; lonais; asturolonais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ath','','Athapascan languages','athapascanes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('aus','','Australian languages','australiennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ava','av','Avaric','avar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ave','ae','Avestan','avestique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('awa','','Awadhi','awadhi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('aym','ay','Aymara','aymara');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('aze','az','Azerbaijani','azri');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bad','','Banda languages','banda, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bai','','Bamileke languages','bamilk, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bak','ba','Bashkir','bachkir');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bal','','Baluchi','baloutchi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bam','bm','Bambara','bambara');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ban','','Balinese','balinais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('baq','eu','Basque','basque');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bas','','Basa','basa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bat','','Baltic languages','baltes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bej','','Beja; Bedawiyet','bedja');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bel','be','Belarusian','bilorusse');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bem','','Bemba','bemba');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ben','bn','Bengali','bengali');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ber','','Berber languages)','berbres, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bho','','Bhojpuri','bhojpuri');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bih','bh','Bihari','bihari');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bik','','Bikol','bikol');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bin','','Bini; Edo','bini; edo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bis','bi','Bislama','bichlamar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bla','','Siksika','blackfoot');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bnt','','Bantu languages','bantou, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bos','bs','Bosnian','bosniaque');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bra','','Braj','braj');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bre','br','Breton','breton');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('btk','','Batak languages','batak, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bua','','Buriat','bouriate');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bug','','Buginese','bugi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bul','bg','Bulgarian','bulgare');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('bur','my','Burmese','birman');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('byn','','Blin; Bilin','blin; bilen');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cad','','Caddo','caddo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cai','','Central American Indian languages','amrindiennes de l''Amrique centrale, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('car','','Galibi Carib','karib; galibi; carib');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cat','ca','Catalan; Valencian','catalan; valencien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cau','','Caucasian languages','caucasiennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ceb','','Cebuano','cebuano');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cel','','Celtic languages','celtiques, langues; celtes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cha','ch','Chamorro','chamorro');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chb','','Chibcha','chibcha');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('che','ce','Chechen','tchtchne');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chg','','Chagatai','djaghata');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chi','zh','Chinese','chinois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chk','','Chuukese','chuuk');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chm','','Mari','mari');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chn','','Chinook jargon','chinook, jargon');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cho','','Choctaw','choctaw');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chp','','Chipewyan; Dene Suline','chipewyan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chr','','Cherokee','cherokee');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chu','cu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','slavon d''glise; vieux slave; slavon liturgique; vieux bulgare');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chv','cv','Chuvash','tchouvache');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('chy','','Cheyenne','cheyenne');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cmc','','Chamic languages','chames, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cop','','Coptic','copte');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cor','kw','Cornish','cornique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cos','co','Corsican','corse');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cpe','','Creoles and pidgins, English based','croles et pidgins bass sur l''anglais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cpf','','Creoles and pidgins, French-based','croles et pidgins bass sur le franais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cpp','','Creoles and pidgins, Portuguese-based','croles et pidgins bass sur le portugais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cre','cr','Cree','cree');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('crh','','Crimean Tatar; Crimean Turkish','tatar de Crim');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('crp','','Creoles and pidgins','croles et pidgins');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('csb','','Kashubian','kachoube');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cus','','Cushitic languages','couchitiques, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('cze','cs','Czech','tchque');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dak','','Dakota','dakota');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dan','da','Danish','danois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dar','','Dargwa','dargwa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('day','','Land Dayak languages','dayak, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('del','','Delaware','delaware');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('den','','Slave (Athapascan)','esclave (athapascan)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dgr','','Dogrib','dogrib');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('din','','Dinka','dinka');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('div','dv','Divehi; Dhivehi; Maldivian','maldivien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('doi','','Dogri','dogri');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dra','','Dravidian languages','dravidiennes,langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dsb','','Lower Sorbian','bas-sorabe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dua','','Duala','douala');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dum','','Dutch, Middle (ca.1050-1350)','nerlandais moyen (ca. 1050-1350)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dut','nl','Dutch; Flemish','nerlandais; flamand');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dyu','','Dyula','dioula');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('dzo','dz','Dzongkha','dzongkha');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('efi','','Efik','efik');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('egy','','Egyptian (Ancient)','gyptien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('eka','','Ekajuk','ekajuk');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('elx','','Elamite','lamite');
INSERT INTO language (code,iso_639_1,name,french_name,sort_order) VALUES ('eng','en','English','anglais',1);
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('enm','','English, Middle (1100-1500)','anglais moyen (1100-1500)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('epo','eo','Esperanto','espranto');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('est','et','Estonian','estonien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ewe','ee','Ewe','w');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ewo','','Ewondo','wondo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fan','','Fang','fang');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fao','fo','Faroese','froen');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fat','','Fanti','fanti');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fij','fj','Fijian','fidjien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fil','','Filipino; Pilipino','filipino; pilipino');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fin','fi','Finnish','finnois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fiu','','Finno-Ugrian languages)','finno-ougriennes,langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fon','','Fon','fon');
INSERT INTO language (code,iso_639_1,name,french_name,sort_order) VALUES ('fre','fr','French','franais',3);
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('frm','','French, Middle (ca.1400-1600)','franais moyen (1400-1600)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fro','','French, Old (842-ca.1400)','franais ancien (842-ca.1400)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('frr','','Northern Frisian','frison septentrional');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('frs','','Eastern Frisian','frison oriental');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fry','fy','Western Frisian','frison occidental');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ful','ff','Fulah','peul');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('fur','','Friulian','frioulan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gaa','','Ga','ga');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gay','','Gayo','gayo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gba','','Gbaya','gbaya');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gem','','Germanic languages','germaniques, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('geo','ka','Georgian','gorgien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ger','de','German','allemand');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gez','','Geez','guze');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gil','','Gilbertese','kiribati');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gla','gd','Gaelic; Scottish Gaelic','galique; galique cossais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gle','ga','Irish','irlandais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('glg','gl','Galician','galicien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('glv','gv','Manx','manx; mannois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gmh','','German, Middle High (ca.1050-1500)','allemand, moyen haut (ca. 1050-1500)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('goh','','German, Old High (ca.750-1050)','allemand, vieux haut (ca. 750-1050)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gon','','Gondi','gond');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gor','','Gorontalo','gorontalo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('got','','Gothic','gothique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('grb','','Grebo','grebo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('grc','','Greek, Ancient (to 1453)','grec ancien (jusqu'' 1453)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gre','el','Greek, Modern (1453-)','grec moderne (aprs 1453)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('grn','gn','Guarani','guarani');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gsw','','Swiss German; Alemannic; Alsatian','suisse almanique; almanique; alsacien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('guj','gu','Gujarati','goudjrati');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('gwi','','Gwich''in','gwich''in');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hai','','Haida','haida');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hat','ht','Haitian; Haitian Creole','hatien; crole hatien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hau','ha','Hausa','haoussa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('haw','','Hawaiian','hawaen');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('heb','he','Hebrew','hbreu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('her','hz','Herero','herero');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hil','','Hiligaynon','hiligaynon');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('him','','Himachali','himachali');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hin','hi','Hindi','hindi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hit','','Hittite','hittite');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hmn','','Hmong','hmong');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hmo','ho','Hiri Motu','hiri motu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hrv','hr','Croatian','croate');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hsb','','Upper Sorbian','haut-sorabe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hun','hu','Hungarian','hongrois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('hup','','Hupa','hupa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('iba','','Iban','iban');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ibo','ig','Igbo','igbo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ice','is','Icelandic','islandais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ido','io','Ido','ido');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('iii','ii','Sichuan Yi; Nuosu','yi de Sichuan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ijo','','Ijo languages','ijo, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('iku','iu','Inuktitut','inuktitut');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ile','ie','Interlingue; Occidental','interlingue');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ilo','','Iloko','ilocano');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ina','ia','Interlingua (International Auxiliary Language Association)','interlingua (langue auxiliaire internationale)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('inc','','Indic languages','indo-aryennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ind','id','Indonesian','indonsien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ine','','Indo-European languages','indo-europennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('inh','','Ingush','ingouche');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ipk','ik','Inupiaq','inupiaq');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ira','','Iranian languages','iraniennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('iro','','Iroquoian languages','iroquoises, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ita','it','Italian','italien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('jav','jv','Javanese','javanais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('jbo','','Lojban','lojban');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('jpn','ja','Japanese','japonais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('jpr','','Judeo-Persian','judo-persan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('jrb','','Judeo-Arabic','judo-arabe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kaa','','Kara-Kalpak','karakalpak');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kab','','Kabyle','kabyle');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kac','','Kachin; Jingpho','kachin; jingpho');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kal','kl','Kalaallisut; Greenlandic','groenlandais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kam','','Kamba','kamba');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kan','kn','Kannada','kannada');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kar','','Karen languages','karen, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kas','ks','Kashmiri','kashmiri');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kau','kr','Kanuri','kanouri');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kaw','','Kawi','kawi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kaz','kk','Kazakh','kazakh');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kbd','','Kabardian','kabardien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kha','','Khasi','khasi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('khi','','Khoisan languages','khosan, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('khm','km','Central Khmer','khmer central');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kho','','Khotanese; Sakan','khotanais; sakan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kik','ki','Kikuyu; Gikuyu','kikuyu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kin','rw','Kinyarwanda','rwanda');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kir','ky','Kirghiz; Kyrgyz','kirghiz');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kmb','','Kimbundu','kimbundu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kok','','Konkani','konkani');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kom','kv','Komi','kom');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kon','kg','Kongo','kongo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kor','ko','Korean','coren');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kos','','Kosraean','kosrae');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kpe','','Kpelle','kpell');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('krc','','Karachay-Balkar','karatchai balkar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('krl','','Karelian','carlien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kro','','Kru languages','krou, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kru','','Kurukh','kurukh');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kua','kj','Kuanyama; Kwanyama','kuanyama; kwanyama');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kum','','Kumyk','koumyk');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kur','ku','Kurdish','kurde');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('kut','','Kutenai','kutenai');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lad','','Ladino','judo-espagnol');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lah','','Lahnda','lahnda');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lam','','Lamba','lamba');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lao','lo','Lao','lao');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lat','la','Latin','latin');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lav','lv','Latvian','letton');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lez','','Lezghian','lezghien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lim','li','Limburgan; Limburger; Limburgish','limbourgeois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lin','ln','Lingala','lingala');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lit','lt','Lithuanian','lituanien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lol','','Mongo','mongo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('loz','','Lozi','lozi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ltz','lb','Luxembourgish; Letzeburgesch','luxembourgeois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lua','','Luba-Lulua','luba-lulua');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lub','lu','Luba-Katanga','luba-katanga');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lug','lg','Ganda','ganda');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lui','','Luiseno','luiseno');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lun','','Lunda','lunda');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('luo','','Luo (Kenya and Tanzania)','luo (Kenya et Tanzanie)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('lus','','Lushai','lushai');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mac','mk','Macedonian','macdonien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mad','','Madurese','madourais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mag','','Magahi','magahi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mah','mh','Marshallese','marshall');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mai','','Maithili','maithili');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mak','','Makasar','makassar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mal','ml','Malayalam','malayalam');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('man','','Mandingo','mandingue');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mao','mi','Maori','maori');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('map','','Austronesian languages','austronsiennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mar','mr','Marathi','marathe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mas','','Masai','massa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('may','ms','Malay','malais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mdf','','Moksha','moksa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mdr','','Mandar','mandar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('men','','Mende','mend');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mga','','Irish, Middle (900-1200)','irlandais moyen (900-1200)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mic','','Mi''kmaq; Micmac','mi''kmaq; micmac');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('min','','Minangkabau','minangkabau');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mkh','','Mon-Khmer languages','mn-khmer, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mlg','mg','Malagasy','malgache');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mlt','mt','Maltese','maltais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mnc','','Manchu','mandchou');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mni','','Manipuri','manipuri');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mno','','Manobo languages','manobo, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('moh','','Mohawk','mohawk');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mon','mn','Mongolian','mongol');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mos','','Mossi','mor');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mul','','Multiple languages','multilingue');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mun','','Munda languages','mounda, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mus','','Creek','muskogee');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mwl','','Mirandese','mirandais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('mwr','','Marwari','marvari');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('myn','','Mayan languages','maya, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('myv','','Erzya','erza');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nah','','Nahuatl languages','nahuatl, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nai','','North American Indian languages','nordamrindiennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nap','','Neapolitan','napolitain');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nau','na','Nauru','nauruan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nav','nv','Navajo; Navaho','navaho');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nbl','nr','Ndebele, South; South Ndebele','ndbl du Sud');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nde','nd','Ndebele, North; North Ndebele','ndbl du Nord');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ndo','ng','Ndonga','ndonga');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nds','','Low German; Low Saxon; German, Low; Saxon, Low','bas allemand; bas saxon; allemand, bas; saxon, bas');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nep','ne','Nepali','npalais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('new','','Nepal Bhasa; Newari','nepal bhasa; newari');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nia','','Nias','nias');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nic','','Niger-Kordofanian languages','nigro-kordofaniennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('niu','','Niuean','niu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nno','nn','Norwegian Nynorsk; Nynorsk, Norwegian','norvgien nynorsk; nynorsk, norvgien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nob','nb','Bokml, Norwegian; Norwegian Bokml','norvgien bokml');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nog','','Nogai','noga; nogay');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('non','','Norse, Old','norrois, vieux');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nor','no','Norwegian','norvgien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nqo','','N''Ko','n''ko');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nso','','Pedi; Sepedi; Northern Sotho','pedi; sepedi; sotho du Nord');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nub','','Nubian languages','nubiennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nwc','','Classical Newari; Old Newari; Classical Nepal Bhasa','newari classique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nya','ny','Chichewa; Chewa; Nyanja','chichewa; chewa; nyanja');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nym','','Nyamwezi','nyamwezi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nyn','','Nyankole','nyankol');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nyo','','Nyoro','nyoro');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('nzi','','Nzima','nzema');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('oci','oc','Occitan (post 1500)','occitan (aprs 1500)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('oji','oj','Ojibwa','ojibwa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ori','or','Oriya','oriya');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('orm','om','Oromo','galla');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('osa','','Osage','osage');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('oss','os','Ossetian; Ossetic','osste');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ota','','Turkish, Ottoman (1500-1928)','turc ottoman (1500-1928)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('oto','','Otomian languages','otomi, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('paa','','Papuan languages','papoues, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pag','','Pangasinan','pangasinan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pal','','Pahlavi','pahlavi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pam','','Pampanga; Kapampangan','pampangan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pan','pa','Panjabi; Punjabi','pendjabi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pap','','Papiamento','papiamento');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pau','','Palauan','palau');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('peo','','Persian, Old (ca.600-400 B.C.)','perse, vieux (ca. 600-400 av. J.-C.)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('per','fa','Persian','persan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('phi','','Philippine languages)','philippines, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('phn','','Phoenician','phnicien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pli','pi','Pali','pali');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pol','pl','Polish','polonais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pon','','Pohnpeian','pohnpei');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('por','pt','Portuguese','portugais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pra','','Prakrit languages','prkrit, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pro','','Provenal, Old (to 1500);Occitan, Old (to 1500)','provenal ancien (jusque'' 1500); occitan ancien (jusque'' 1500)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('pus','ps','Pushto; Pashto','pachto');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('que','qu','Quechua','quechua');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('raj','','Rajasthani','rajasthani');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('rap','','Rapanui','rapanui');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('rar','','Rarotongan; Cook Islands Maori','rarotonga; maori des les Cook');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('roa','','Romance languages','romanes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('roh','rm','Romansh','romanche');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('rom','','Romany','tsigane');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('rum','ro','Romanian; Moldavian; Moldovan','roumain; moldave');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('run','rn','Rundi','rundi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('rup','','Aromanian; Arumanian; Macedo-Romanian','aroumain; macdo-roumain');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('rus','ru','Russian','russe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sad','','Sandawe','sandawe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sag','sg','Sango','sango');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sah','','Yakut','iakoute');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sai','','South American Indian languages','sud-amrindiennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sal','','Salishan languages','salishennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sam','','Samaritan Aramaic','samaritain');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('san','sa','Sanskrit','sanskrit');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sas','','Sasak','sasak');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sat','','Santali','santal');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('scn','','Sicilian','sicilien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sco','','Scots','cossais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sel','','Selkup','selkoupe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sem','','Semitic languages','smitiques, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sga','','Irish, Old (to 900)','irlandais ancien (jusque'' 900)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sgn','','Sign Languages','langues des signes');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('shn','','Shan','chan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sid','','Sidamo','sidamo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sin','si','Sinhala; Sinhalese','singhalais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sio','','Siouan languages','sioux, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sit','','Sino-Tibetan languages','sino-tibtaines, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sla','','Slavic languages','slaves, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('slo','sk','Slovak','slovaque');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('slv','sl','Slovenian','slovne');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sma','','Southern Sami','sami du Sud');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sme','se','Northern Sami','sami du Nord');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('smi','','Sami languages','sames, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('smj','','Lule Sami','sami de Lule');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('smn','','Inari Sami','sami d''Inari');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('smo','sm','Samoan','samoan');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sms','','Skolt Sami','sami skolt');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sna','sn','Shona','shona');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('snd','sd','Sindhi','sindhi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('snk','','Soninke','sonink');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sog','','Sogdian','sogdien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('som','so','Somali','somali');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('son','','Songhai languages','songhai, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sot','st','Sotho, Southern','sotho du Sud');
INSERT INTO language (code,iso_639_1,name,french_name,sort_order) VALUES ('spa','es','Spanish; Castilian','espagnol; castillan',2);
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('srd','sc','Sardinian','sarde');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('srn','','Sranan Tongo','sranan tongo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('srp','sr','Serbian','serbe');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('srr','','Serer','srre');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ssa','','Nilo-Saharan languages','nilo-sahariennes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ssw','ss','Swati','swati');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('suk','','Sukuma','sukuma');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sun','su','Sundanese','soundanais');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sus','','Susu','soussou');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('sux','','Sumerian','sumrien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('swa','sw','Swahili','swahili');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('swe','sv','Swedish','sudois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('syc','','Classical Syriac','syriaque classique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('syr','','Syriac','syriaque');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tah','ty','Tahitian','tahitien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tai','','Tai languages','tai, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tam','ta','Tamil','tamoul');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tat','tt','Tatar','tatar');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tel','te','Telugu','tlougou');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tem','','Timne','temne');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ter','','Tereno','tereno');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tet','','Tetum','tetum');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tgk','tg','Tajik','tadjik');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tgl','tl','Tagalog','tagalog');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tha','th','Thai','tha');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tib','bo','Tibetan','tibtain');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tig','','Tigre','tigr');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tir','ti','Tigrinya','tigrigna');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tiv','','Tiv','tiv');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tkl','','Tokelau','tokelau');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tlh','','Klingon; tlhIngan-Hol','klingon');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tli','','Tlingit','tlingit');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tmh','','Tamashek','tamacheq');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tog','','Tonga (Nyasa)','tonga (Nyasa)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ton','to','Tonga (Tonga Islands)','tongan (les Tonga)');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tpi','','Tok Pisin','tok pisin');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tsi','','Tsimshian','tsimshian');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tsn','tn','Tswana','tswana');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tso','ts','Tsonga','tsonga');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tuk','tk','Turkmen','turkmne');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tum','','Tumbuka','tumbuka');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tup','','Tupi languages','tupi, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tur','tr','Turkish','turc');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tut','','Altaic languages','altaques, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tvl','','Tuvalu','tuvalu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('twi','tw','Twi','twi');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('tyv','','Tuvinian','touva');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('udm','','Udmurt','oudmourte');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('uga','','Ugaritic','ougaritique');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('uig','ug','Uighur; Uyghur','ougour');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ukr','uk','Ukrainian','ukrainien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('umb','','Umbundu','umbundu');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('und','','Undetermined','indtermine');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('urd','ur','Urdu','ourdou');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('uzb','uz','Uzbek','ouszbek');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('vai','','Vai','va');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ven','ve','Venda','venda');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('vie','vi','Vietnamese','vietnamien');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('vol','vo','Volapk','volapk');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('vot','','Votic','vote');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('wak','','Wakashan languages','wakashanes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('wal','','Wolaitta; Wolaytta','wolaitta; wolaytta');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('war','','Waray','waray');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('was','','Washo','washo');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('wel','cy','Welsh','gallois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('wen','','Sorbian languages','sorabes, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('wln','wa','Walloon','wallon');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('wol','wo','Wolof','wolof');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('xal','','Kalmyk; Oirat','kalmouk; orat');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('xho','xh','Xhosa','xhosa');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('yao','','Yao','yao');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('yap','','Yapese','yapois');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('yid','yi','Yiddish','yiddish');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('yor','yo','Yoruba','yoruba');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('ypk','','Yupik languages','yupik, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zap','','Zapotec','zapotque');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zbl','','Blissymbols; Blissymbolics; Bliss','symboles Bliss; Bliss');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zen','','Zenaga','zenaga');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zha','za','Zhuang; Chuang','zhuang; chuang');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('znd','','Zande languages','zand, langues');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zul','zu','Zulu','zoulou');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zun','','Zuni','zuni');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zxx','','No linguistic content; Not applicable','pas de contenu linguistique; non applicable');
INSERT INTO language (code,iso_639_1,name,french_name) VALUES ('zza','','Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki','zaza; dimili; dimli; kirdki; kirmanjki; zazaki');
